export default defineNuxtConfig({
  app: {
    // baseURL: "/",
    // buildAssetsDir: 'assets',
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no',
      title: 'Perhitungan Gizi Puskesmas.',
      meta: [
        { name: 'keywords', content: 'Site keywords here' },
        { name: 'description', content: '' },
        { name: 'copyright', content: '' },
        { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' },
      ],
      link: [
        { rel: 'icon', type: 'image/png', href: '/assets/img/favicon.png' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap' },
        { rel: 'stylesheet', href: '/assets/css/bootstrap.min.css' },
        { rel: 'stylesheet', href: '/assets/css/nice-select.css' },
        { rel: 'stylesheet', href: '/assets/css/font-awesome.min.css' },
        { rel: 'stylesheet', href: '/assets/css/icofont.css' },
        { rel: 'stylesheet', href: '/assets/css/slicknav.min.css' },
        { rel: 'stylesheet', href: '/assets/css/owl-carousel.css' },
        { rel: 'stylesheet', href: '/assets/css/datepicker.css' },
        { rel: 'stylesheet', href: '/assets/css/animate.min.css' },
        { rel: 'stylesheet', href: '/assets/css/magnific-popup.css' },
        { rel: 'stylesheet', href: '/assets/css/normalize.css' },
        { rel: 'stylesheet', href: '/assets/style.css' },
        { rel: 'stylesheet', href: '/assets/css/responsive.css' },
        { rel: 'stylesheet', href: 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' },
      ],
      script: [
        { src: '/assets/js/jquery.min.js', defer: true },
        { src: '/assets/js/jquery-migrate-3.0.0.js', defer: true },
        { src: '/assets/js/jquery-ui.min.js', defer: true },
        { src: '/assets/js/easing.js', defer: true },
        { src: '/assets/js/colors.js', defer: true },
        { src: '/assets/js/popper.min.js', defer: true },
        { src: '/assets/js/bootstrap-datepicker.js', defer: true },
        { src: '/assets/js/jquery.nav.js', defer: true },
        { src: '/assets/js/slicknav.min.js', defer: true },
        { src: '/assets/js/jquery.scrollUp.min.js', defer: true },
        { src: '/assets/js/niceselect.js', defer: true },
        { src: '/assets/js/tilt.jquery.min.js', defer: true },
        { src: '/assets/js/owl-carousel.js', defer: true },
        { src: '/assets/js/jquery.counterup.min.js', defer: true },
        { src: '/assets/js/steller.js', defer: true },
        { src: '/assets/js/wow.min.js', defer: true },
        { src: '/assets/js/jquery.magnific-popup.min.js', defer: true },
        { src: 'https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js', defer: true },
        { src: '/assets/js/bootstrap.min.js', defer: true },
        { src: '/assets/js/main.js', defer: true },
        { src: 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js', defer: true },
        { src: 'https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=', defer: true },
        { src: 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js', defer: true },
      ],
    },
  },

  css: [
    '@/assets/css/bootstrap.min.css',
    '@/assets/css/nice-select.css',
    '@/assets/css/font-awesome.min.css',
    '@/assets/css/icofont.css',
    '@/assets/css/slicknav.min.css',
    '@/assets/css/owl-carousel.css',
    '@/assets/css/datepicker.css',
    '@/assets/css/animate.min.css',
    '@/assets/css/magnific-popup.css',
    '@/assets/css/normalize.css',
    '@/assets/style.css',
    '@/assets/css/responsive.css',
    'handsontable/styles/handsontable.min.css',
    'handsontable/styles/ht-theme-main.min.css',
    'vue-multiselect/dist/vue-multiselect.css'
  ],

  compatibilityDate: '2025-02-13',
  modules: ['nuxt-auth-utils'],
});